= Packages to Install

Eventually I am going to flush this out into a full install script.
For now the idea is just to make sure I have a list of what I've installed and why.  It will replace a page I've had going in Notion.  Assume Arch-based distro.

== Pacman

flatpak
stow
zsh
zsh-syntax-highlighting
zsh-autosuggestions
tree
vim
neovim
speedtest-cli
gamemode
gnome-bluetooth
lynx
python
neofetch
nss-mdns # for printing to Brother Printer
variety # Wallpaper slideshow
tldr
ffmpeg
feh # image viewer that plays nicer with epr
fzf
zellij
nerd-fonts # Need to replace with a single, less-heavy font.
pandoc
fzf
texlive-latexmk (includes lots of TeX stuff) 
tree-sitter

== AUR

timeshift
timeshift-autosnap
chrome-gnome-shell # allows installing extensions from website.
ttf-ms-fonts
protonvpn-cli
input-remapper-git
multimc-bin #probably go back to flatpak
thinkfan-ui # Would like to find a cleaner way
photocollage # When Google Photos Collage doesn't cut it.
epr-git # ePub reader - switch to epy?
recutils
fireplace-git

== Flatpak

com.github.tchx84.Flatseal
com.jaquadro.NBTExplorer
us.zoom.Zoom
com.microsoft.Teams
com.github.jeromerobert.pdfarranger
com.google.Chrome
